[package]
name = "qubit-reflect-derive"
version = "0.1.0"
edition = "2024"
rust-version = "1.94"
authors = ["Haixing Hu <starfish.hu@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/qubit-ltd/rs-reflect"
description = "Procedural macros for qubit-reflect"
homepage = "https://github.com/qubit-ltd/rs-reflect"
documentation = "https://docs.rs/qubit-reflect-derive"
keywords = ["reflection", "metadata", "derive", "macro", "qubit"]
categories = ["development-tools"]

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "3"
proc-macro2 = { version = "1", features = ["span-locations"] }
quote = "1"
syn = { version = "2", features = ["full", "extra-traits"] }
