// =============================================================================
//    Copyright (c) 2025 - 2026 Haixing Hu.
//
//    SPDX-License-Identifier: Apache-2.0
//
//    Licensed under the Apache License, Version 2.0.
// =============================================================================

//! Macro-based structural and executable reflection for Rust.
//!
//! The crate is currently a requirements-first scaffold. Its public reflection
//! API has not been implemented or stabilized yet.

#![forbid(unsafe_code)]

/// APIs for reflected field and variant access.
pub mod access;
/// Built-in reflected type descriptors.
pub mod builtin;
/// Capability descriptors for reflected types.
pub mod capability;
/// Construction APIs for reflected values.
pub mod construct;
/// Type and member descriptor APIs.
pub mod descriptor;
/// Reflection error types.
pub mod error;
/// Type expression and generic definition APIs.
pub mod expression;
/// Type identity and naming APIs.
pub mod identity;
/// Invocation APIs for reflected methods.
pub mod invoke;
/// Reflection registry APIs.
pub mod registry;
/// Dynamic value APIs.
pub mod value;

#[cfg(feature = "derive")]
pub use qubit_reflect_derive::{Reflect, reflect, reflect_impl};

/// Internal dependencies needed by code generated by reflection macros.
#[doc(hidden)]
#[path = "private/mod.rs"]
pub mod __private;
