// =============================================================================
//    Copyright (c) 2025 - 2026 Haixing Hu.
//
//    SPDX-License-Identifier: Apache-2.0
//
//    Licensed under the Apache License, Version 2.0.
// =============================================================================

//! Macro-based structural and executable reflection for Rust.
//!
//! The crate is currently a requirements-first scaffold. Its public reflection
//! API has not been implemented or stabilized yet.

#![forbid(unsafe_code)]

/// APIs for reflected field and variant access.
pub mod access;
/// Built-in reflected type descriptors.
pub mod builtin;
/// Capability descriptors for reflected types.
pub mod capability;
/// Construction APIs for reflected values.
pub mod construct;
/// Type and member descriptor APIs.
pub mod descriptor;
/// Reflection error types.
pub mod error;
/// Type expression and generic definition APIs.
pub mod expression;
/// Type identity and naming APIs.
pub mod identity;
/// Invocation APIs for reflected methods.
pub mod invoke;
/// Reflection registry APIs.
pub mod registry;
/// Dynamic value APIs.
pub mod value;

/// Dynamic construction errors and owned recovery payloads.
pub use construct::ConstructionError;
/// Dynamic construction errors and owned recovery payloads.
pub use construct::ConstructionRecovery;
/// Dynamic construction input for named struct and variant fields.
pub use construct::NamedConstructionInput;
/// Dynamic owned base plus named replacement fields for a struct update.
pub use construct::StructUpdateInput;
/// Dynamic construction input for tuple struct and variant fields.
pub use construct::TupleConstructionInput;
/// Common descriptor navigation types.
pub use descriptor::ConcreteGenericDescriptor;
/// Common descriptor navigation types.
pub use descriptor::FieldDescriptor;
/// The static reflection contract implemented by reflected Rust types.
pub use descriptor::Reflect;
/// The immutable root descriptor for a reflected Rust type.
pub use descriptor::TypeDescriptor;
/// Common descriptor navigation types.
pub use descriptor::VariantDescriptor;
#[cfg(feature = "derive")]
pub use qubit_reflect_derive::Reflect;
#[cfg(feature = "derive")]
pub use qubit_reflect_derive::reflect;
#[cfg(feature = "derive")]
pub use qubit_reflect_derive::reflect_impl;
/// The effective implementation and method view for one registered root.
pub use registry::EffectiveTypeView;
/// The immutable global registry of linked reflection fragments.
pub use registry::ReflectRegistry;
/// Local-mode mutable dynamic borrow.
pub use value::ReflectedMut;
/// Local-mode owned dynamic value.
pub use value::ReflectedOwned;
/// Local-mode shared dynamic borrow.
pub use value::ReflectedRef;
/// Thread-safe mutable dynamic borrow.
pub use value::SendReflectedMut;
/// Thread-safe owned dynamic value.
pub use value::SendReflectedOwned;
/// Thread-safe shared dynamic borrow.
pub use value::SendReflectedRef;

/// Internal dependencies needed by code generated by reflection macros.
#[doc(hidden)]
#[path = "private/mod.rs"]
pub mod __private;
